# .github/workflows/ci.yml
name: python CI

# Trigger the workflows on any push to the main branch or pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v2
    
      # Step 2: setup the pthon environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
      # Step 3: install Dependencies  
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
         
      # step 4: Run tests  
    - name: Run tests
      run: pytest
